### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by SaurabhChawda**

### CODE REVIEW

**Review by harshitadaswani — COMMENTED** [review]
Few suggestions: 
- use lower z-index values
- avoid the use of pixels in width

Apart from that, everything looks good!

**Comment by SaurabhChawda** [comment]
> Few suggestions:
> 
> * use lower z-index values
> * avoid the use of pixels in width
> 
> Apart from that, everything looks good!

Sure , Thank You

**Review by talrejah02 — APPROVED** [review]
Suggestion:- prefer rem or em for margin and padding so that it gets responsiveness.

Apart from this, Good to go.

**Comment by SaurabhChawda** [comment]
> Suggestion:- prefer rem or em for margin and padding so that it gets responsiveness.
> 
> Apart from this, Good to go.

Okay,ThankYou

**Pull request merged**
