### PR TITLE
List component

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Added List Component in Aqua_UI.
Screenshot (301)

### CODE REVIEW

**Review by ShreyashMahajan — APPROVED** [review]
code looks good to merge

**Review by sushil-mod — APPROVED** [review]
i like your UI , your variants of list is also good .

**Comment by SaurabhChawda** [comment]
> code looks good to merge

ThankYou

**Comment by SaurabhChawda** [comment]
> i like your UI , your variants of list is also good .

Thankyou

**Pull request merged**
