### PR TITLE
Feat : Added Rating Component.

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Added Rating Component in Aqua_UI Component Library.
Screenshot (305)

### CODE REVIEW

**Review by ajit-sharmaGH — APPROVED** [review]
Looks good you can merge it

**Review by fahd23 — APPROVED** [review]
code looks good

**Comment by SaurabhChawda** [comment]
> Looks good you can merge it

ThankYou

**Comment by SaurabhChawda** [comment]
> 

ThankYou

**Pull request merged**
