### PR TITLE
Sidebar hamburger links

### PR DESCRIPTION
**Pull request by SaurabhChawda**
Updated sidebar and hamburger links.
Screenshot (321)

### CODE REVIEW

**Review by ShreyashMahajan — APPROVED** [review]
Code looks neat and clean and good to merge

**Review by sks-21 — APPROVED** [review]
The code looks nice. Good to merge
- Good naming convention
- Clean code
- Proper values of units

**Comment by SaurabhChawda** [comment]
> The code looks nice. Good to merge
> 
> * Good naming convention
> * Clean code
> * Proper values of units

ThankYou

**Comment by SaurabhChawda** [comment]
> Code looks neat and clean and good to merge

ThankYou

**Pull request merged**
